require("pratulmuthuraja.plugins-setup")
require("pratulmuthuraja.core.options")
require("pratulmuthuraja.core.keymaps")
require("pratulmuthuraja.core.colorscheme")
require("pratulmuthuraja.plugins.comment")
require("pratulmuthuraja.plugins.nvim-tree")
require("pratulmuthuraja.plugins.lualine")
require("pratulmuthuraja.plugins.telescope")
require("pratulmuthuraja.plugins.nvim-cmp")
require("pratulmuthuraja.plugins.lsp.mason")
require("pratulmuthuraja.plugins.lsp.lspsaga")
require("pratulmuthuraja.plugins.lsp.lspconfig")
require("pratulmuthuraja.plugins.lsp.null-ls")
require("pratulmuthuraja.plugins.autopairs")
require("pratulmuthuraja.plugins.treesitter")
require("pratulmuthuraja.plugins.gitsigns")

