require("pratulmuthuraja.plugins-setup")
require("pratulmuthuraja.core.options")
require("pratulmuthuraja.core.keymaps")
require("pratulmuthuraja.core.colorscheme")
require("pratulmuthuraja.plugins.comment")
require("pratulmuthuraja.plugins.nvim-tree")
require("pratulmuthuraja.plugins.lualine")
